---
- !ruby/object:Yauth::User
  username: foo
  password: !ruby/string:BCrypt::Password
    str: !binary |-
      JDJhJDEwJEcvV1J6OXpjaHNMSFMyeUtlUy9ibGVqZ1V4d05EVjhMQWVHYzRm
      ZTV4WUhZSVk3MTN4eXFL
    version: !ruby/string:BCrypt::Password |-
      MmE=
    cost: 10
    salt: !binary |-
      JDJhJDEwJEcvV1J6OXpjaHNMSFMyeUtlUy9ibGU=
    checksum: !binary |-
      amdVeHdORFY4TEFlR2M0ZmU1eFlIWUlZNzEzeHlxSw==
  plain_password: bar
